"""initial schema

Revision ID: 730cf63cba2a
Revises:
Create Date: 2026-08-04 21:36:51.576562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '730cf63cba2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acs_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('bearer_token_encrypted', sa.Text(), nullable=True),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('online_threshold_s', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('approved_dns', sa.JSON(), nullable=False),
    sa.Column('online_threshold_s', sa.Integer(), nullable=False),
    sa.Column('diagnostic_cooldown_s', sa.Integer(), nullable=False),
    sa.Column('diagnostic_timeout_s', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('crypto_key_fp', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_status'), 'audit_events', ['status'], unique=False)
    op.create_index(op.f('ix_audit_events_target'), 'audit_events', ['target'], unique=False)
    op.create_table('diagnostic_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=512), nullable=False),
    sa.Column('acs_server_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_runs_device_id'), 'diagnostic_runs', ['device_id'], unique=False)
    op.create_table('firmware_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('product_class', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_packages_product_class'), 'firmware_packages', ['product_class'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_acs_server_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_index(op.f('ix_firmware_packages_product_class'), table_name='firmware_packages')
    op.drop_table('firmware_packages')
    op.drop_index(op.f('ix_diagnostic_runs_device_id'), table_name='diagnostic_runs')
    op.drop_table('diagnostic_runs')
    op.drop_index(op.f('ix_audit_events_target'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_status'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('app_settings')
    op.drop_table('acs_servers')
    # ### end Alembic commands ###
